# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: Rails.ci

on:
  push:
    branches: [ cicd ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          bundler-cache: true
      # Add or Replace any other security checks here
      - name: Run security checks
        - uses: actions/checkout@v1
          - uses: actions/cache@v1
            with:
            path: vendor/bundle
            key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: Run linters
        run: |
          bin/rubocop --parallel
      - name: bundle install
        run: |
          gem install bundler
          bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
      - name: run rspec
        run: bundle exec rspec
      - name: Archive rspec result screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: rspec result screenshots

